# Generated by Django 4.2.4 on 2023-09-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[("ENSEIGNANT", "Enseignant"), ("ETUDIANT", "Etudiant")],
                default="",
                max_length=30,
                verbose_name="Status",
            ),
            preserve_default=False,
        ),
    ]
